// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKFuvAWzLtndJDCscPTCrUda07YuSShk',
    appId: '1:114580263138:web:2ed76b7882cd95a54c8ebb',
    messagingSenderId: '114580263138',
    projectId: 'subliminal-298203',
    authDomain: 'subliminal-298203.firebaseapp.com',
    storageBucket: 'subliminal-298203.appspot.com',
    measurementId: 'G-SPSJ4BSZKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwlyxeYEbo51Io8cc2g3XcsekgoPPmWw4',
    appId: '1:114580263138:android:64f5690252b516864c8ebb',
    messagingSenderId: '114580263138',
    projectId: 'subliminal-298203',
    storageBucket: 'subliminal-298203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_yHY9Shwoz-rFQrl04Qgjf5yG79IsxbU',
    appId: '1:114580263138:ios:308b4450760c19a74c8ebb',
    messagingSenderId: '114580263138',
    projectId: 'subliminal-298203',
    storageBucket: 'subliminal-298203.appspot.com',
    iosClientId: '114580263138-giah64g15fmt8duqmfobr22qnhrophe6.apps.googleusercontent.com',
    iosBundleId: 'com.example.subliminal',
  );
}
