name: subliminal
description: A new Flutter project.
publish_to: 'none'

version: 0.1.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../common/

  bloc: ^8.1.0
  copy_with_extension: ^5.0.0
  firebase_auth: ^4.2.4
  flutter_bloc: ^8.0.1
  firebase_core: ^2.4.1
  flutter_dotenv: ^5.0.2
  firebase_ui_auth: ^1.1.6
  firebase_ui_oauth_google: ^1.0.13
  get_it: ^7.2.0
  go_router: ^6.0.0
  package_info_plus: ^3.0.2
  rest_client: ^2.2.0+5
  rxdart: ^0.27.7
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10
  copy_with_extension_gen: ^5.0.0
  flutter_lints: ^2.0.1

dependency_overrides:
  intl: 0.18.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: DPClear
      fonts:
        - asset: assets/fonts/dp_clear_regular.ttf
          weight: 400
        - asset: assets/fonts/dp_clear_medium.ttf
          weight: 500
