name: subliminal_api
description: The API server for subliminal audio.
version: 0.1.3
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  common:
    path: ../common/

  bloc: ^8.0.2
  dart_dotenv: ^1.0.1
  dcache: ^0.4.0
  equatable: ^2.0.3
  firebase_admin_sdk: ^0.0.2
  get_it: ^7.2.0
  minio: ^3.5.0
  mongo_dart: ^0.7.4
  rest_client: ^2.1.4
  rxdart: ^0.27.3
  secretary: ^0.3.2
  shelf: ^1.2.0
  shelf_cors_headers:
    git:
      url: https://github.com/alexobviously/shelf-cors-headers
      ref: main
  shelf_ndjson_stream: ^0.1.0
  shelf_router: ^1.1.2
  stash: ^4.2.0
  stash_memory: ^4.2.0
  yaml: ^3.1.0
  validators: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
