name: common
description: Common code for sharing between the API and app.
version: 0.1.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  copy_with_extension: ^5.0.0
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  mongo_dart: ^0.7.4
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0
  json_serializable: ^6.2.0
  lints: ^2.0.1
